# Nombre de la aplicación
spring.application.name=tak-manager

# Configuración de Base de Datos H2 
spring.datasource.url=jdbc:h2:mem:takdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Consola de H2 para ver las tablas desde el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostrar las consultas SQL en la consola 
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update